title: FreeFitFuel
url: https://<your-username>.github.io
baseurl: ""   # keep "" if your Pages site is at the repo root; set "/repo-name" for project pages
markdown: kramdown
theme: null
include:
  - assets
  - img
